# active spring profile
spring:
   profiles:
      active: dev

---
# common spring configuration
spring:
   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true

---
# spring dev profile configuration
spring:
   profiles: dev
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: ${db.url}
      username: ${db.username}
      password: ${db.password} 
   jpa:
      database-platform: org.hibernate.dialect.MariaDBDialect
      hibernate:
         ddl-auto: update #create update none
         show-sql: true
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate:
            format_sql: true
            highlight_sql: true

---
# spring production profile configuration
spring:
   profiles: prod

---
# server
server:
   port: 8080
   servlet:
      context-path: /
    
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml